Fix wrong spelling in README.md
open-telemetry/opentelemetry-proto pull request #542
Opened 2024-04-03 05:52 UTC by steverao

Fix wrong spelling in README.md

2024-04-03 07:37 UTC, dmathieu requested changes
This is not a typo. `oneof` is a protobuf field type.
https://protobuf.dev/programming-guides/proto3/#oneof

2024-04-03 07:56 UTC, steverao commented
> This is not a typo. `oneof` is a protobuf field type. https://protobuf.dev/programming-guides/proto3/#oneof

Ok, I am not familiar with it very much：）Is it better to add `` to relevant protobuf keyword to distinguish with normal English word?

2024-04-09 11:20 UTC, arminru approved these changes

2024-04-09 13:22 UTC, yurishkuro approved these changes

2024-04-09 13:22 UTC, merged