Prepare release 1.5.0
open-telemetry/opentelemetry-proto pull request #611
Opened 2024-12-13 02:08 UTC by lmolkova

- profiles: Remove unused `Label` definition. [#602](https://github.com/open-telemetry/opentelemetry-proto/pull/602)
- all: Add note about `schema_url` format (including version). [#605](https://github.com/open-telemetry/opentelemetry-proto/pull/605)
- logs: Add top-level `event_name` field to log records instead of `event.name` attribute. [#600](https://github.com/open-telemetry/opentelemetry-proto/pull/600)

2024-12-13 05:44 UTC, Kielek approved these changes
🎉

2024-12-13 17:54 UTC, cijothomas approved these changes

2024-12-13 19:02 UTC, trask approved these changes

2024-12-13 19:02 UTC, trask commented on CHANGELOG.md
> +## 1.5.0 - 2024-12-12
```suggestion
## 1.5.0 - 2024-12-13
```

2024-12-13 19:04 UTC, jsuereth approved these changes

2024-12-13 19:16 UTC, reyang approved these changes

2024-12-13 21:51 UTC, pellared approved these changes

2024-12-13 21:52 UTC, pellared requested changes

2024-12-13 21:52 UTC, pellared commented on CHANGELOG.md
> +- profiles: Remove unused `Label` definition. [#602](https://github.com/open-telemetry/opentelemetry-proto/pull/602)
Should it not be under ```### Removed`?

2024-12-13 21:52 UTC, pellared commented on CHANGELOG.md
> +- profiles: drop duplicate `attributes` field in message Profile. [#606](https://github.com/open-telemetry/opentelemetry-proto/pull/606)
Should it not be under ```### Removed`?

2024-12-13 23:37 UTC, lmolkova commented on CHANGELOG.md
> +- profiles: Remove unused `Label` definition. [#602](https://github.com/open-telemetry/opentelemetry-proto/pull/602)
sure, pedant 😅

2024-12-14 01:49 UTC, chalin commented
@lmolkova - do the release instructions for this repo also mention https://github.com/open-telemetry/opentelemetry.io/actions/workflows/build-dev.yml? Cf. https://github.com/open-telemetry/semantic-conventions/issues/1009#issuecomment-2541965117

I just ran it now and all seems fine (two external links need to be added to the refcache, but that's not a build error): https://github.com/open-telemetry/opentelemetry.io/actions/runs/12325743342/job/34405496807

2024-12-15 09:48 UTC, pellared approved these changes

2024-12-16 20:32 UTC, marcalff approved these changes

2024-12-17 03:56 UTC, merged